apiVersion: v1
kind: Service
metadata:
  name: home-web2-svc
spec:
  type: NodePort
  selector:
    app: home-web2-static-tmpl
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30036
    